version: '3.1'

services:

  piwigo:
    image: derjudge/piwigo:${PIWIGO_VERSION:-12.2.0}
    restart: unless-stopped
    ports:
      - 80
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      PIWIGO_DB_HOST: ${PIWIGO_DB_HOST:-piwigo-db}
      PIWIGO_DB_NAME: ${PIWIGO_DB_NAME:-piwigo_db}
      PIWIGO_DB_USER: ${PIWIGO_DB_USER:-piwigo_user}
      PIWIGO_DB_PASSWORD: ${PIWIGO_DB_PASSWORD:?err}
      PIWIGO_ADMIN_PASSWORD: ${PIWIGO_ADMIN_PASSWORD:?err}
      PIWIGO_ADMIN_EMAIL: ${PIWIGO_ADMIN_EMAIL:-mail@example.com}
    volumes:
      - app-data:${PIWIGO_VIRTUAL_ROOT:-/var/www/html}
    depends_on:
      piwigo-db:
        condition: service_healthy

  piwigo-db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${PIWIGO_DB_NAME:-piwigo_db}
      MYSQL_USER: ${PIWIGO_DB_USER:-piwigo_user}
      MYSQL_PASSWORD: ${PIWIGO_DB_PASSWORD:?err}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    healthcheck:
      test: "mysql -u${PIWIGO_DB_USER:-piwigo_user} -p${PIWIGO_DB_PASSWORD:?err} ${PIWIGO_DB_NAME:-piwigo_db} -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  app-data:
